name: drupal
recipe: drupal8
config:
  webroot: docroot
  php: '7.3'
  via: nginx
  drush: 9.6.0-rc3
  xdebug: true
services:
  database:
    type: mariadb:10.1
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
proxy:
  mailhog:
    - mail.drupal.lndo.site
tooling:
  robo:
    service: appserver
    description: Runs <robo> commands
    cmd: robo
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  npm:
    service: appserver
  node:
    service: appserver
  gulp:
    service: appserver
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt